Repository sonic-net/sonic-linkmgrd, pull requests merged in 2022-08, with the labels that each got.

#102 [active-active] Update `unhealthy` label definition
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
Labels: Request for 202205 branch

#100 [Active-Standby]Remove unnecessary `handleMuxWaitTimeout` logs
  src/link_manager/LinkManagerStateMachineActiveStandby.cpp
  src/link_manager/LinkManagerStateMachineActiveStandby.h
  test/FakeLinkProber.cpp
  test/FakeLinkProber.h
  test/LinkManagerStateMachineTest.cpp
Labels: Request for 202012 branch, Request for 202205 branch

#104 Fix race condition caused by strand `wrap` method
  src/DbInterface.cpp
  src/DbInterface.h
  src/MuxPort.h
  test/FakeDbInterface.cpp
  test/FakeDbInterface.h
  test/FakeMuxPort.h
  test/LinkManagerStateMachineActiveActiveTest.cpp
  test/MuxManagerTest.cpp
  test/MuxManagerTest.h
Labels: Request for 202012 branch, Request for 202205 branch

#106 Backoff mux probing for server down scenario
  src/link_manager/LinkManagerStateMachineActiveStandby.cpp
  src/link_manager/LinkManagerStateMachineActiveStandby.h
Labels: Request for 202205 branch

#112 Fix lgtm `fatal error: uuid/uuid.h: No such file or directory`
  lgtm.yml
Labels: Request for 202012 branch, Request for 202205 branch

#111 Adjust `DbInterfaceRaceConditionCheck` to Wait Longer for Handlers to be executed
  test/MuxManagerTest.cpp
Labels: Request for 202012 branch, Request for 202205 branch

#117 Update linkmgr health after getting default route update
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  test/FakeDbInterface.cpp
  test/FakeDbInterface.h
  test/FakeMuxPort.h
  test/LinkManagerStateMachineActiveActiveTest.cpp
  test/LinkManagerStateMachineActiveActiveTest.h
Labels: bug, Request for 202205 branch

#123 [active-active] post mux metrics events
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  src/link_manager/LinkManagerStateMachineActiveStandby.h
  src/link_manager/LinkManagerStateMachineBase.h
Labels: Request for 202205 branch

#122 [active-active] Remove unnecessary mux wait timeout logs
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  src/link_manager/LinkManagerStateMachineActiveActive.h
Labels: Request for 202205 branch
