Repository sonic-net/sonic-linkmgrd, pull requests merged in 2023-02, with the labels that each got.

#167 Fix the warning of unused variables
  src/link_prober/LinkProber.cpp
  src/link_prober/LinkProberStateMachineActiveActive.cpp
  test/FakeLinkProber.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#166 Fix mux config when gRPC connection is lost
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  test/LinkManagerStateMachineActiveActiveTest.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#169 [active-active] fix issue that interfaces get stuck in `active` if service starts up with link state down
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  src/link_manager/LinkManagerStateMachineActiveActive.h
  test/LinkManagerStateMachineActiveActiveTest.cpp
Labels: Request for 202205 branch, Request for 202211 branch

#171 [active-active] Toggle to standby if default route is missing
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  test/LinkManagerStateMachineActiveActiveTest.cpp
Labels: Request for 202205 branch

#173 [active-standby] Toggle to standby if link down and config auto
  src/link_manager/LinkManagerStateMachineActiveStandby.cpp
  test/LinkManagerStateMachineTest.cpp
Labels: Request for 202012 branch, Request for 202205 branch

#175 [active-active] link operational down didn't trigger toggle to standby if `MuxUnknown` event arrives first.
  src/link_manager/LinkManagerStateMachineActiveActive.cpp
  test/LinkManagerStateMachineActiveActiveTest.cpp
Labels: Request for 202205 branch, Request for 202211 branch
