Repository sonic-net/sonic-linkmgrd, pull requests merged in 2023-04, with the labels that each got.

#198 [ci] remove hard coded source branch name in azp file
  azure-pipelines.yml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#199 Enable debug symbols
  Makefile
Labels: Request for 202111 branch, Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#203 [codeql] remove hard coded line numbers in `sed` commands
  .github/workflows/codeql-analysis.yml
Labels: Request for 202205 branch

#201 [active-standby][bsl] fix no mux probe issue
  src/link_manager/LinkManagerStateMachineActiveActive.h
  src/link_manager/LinkManagerStateMachineActiveStandby.cpp
  src/link_manager/LinkManagerStateMachineActiveStandby.h
  src/link_manager/LinkManagerStateMachineBase.h
  test/LinkManagerStateMachineTest.cpp
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202211 branch

#182 Support linking to swss logger
  src/DbInterface.cpp
  src/LinkMgrdMain.cpp
  src/common/MuxLogger.cpp
  src/common/MuxLogger.h
  src/common/SwssLogBackend.cpp
  src/common/SwssLogBackend.h
  src/common/subdir.mk
  test/MuxLoggerTest.cpp
  test/MuxLoggerTest.h
  test/subdir.mk
Labels: Request for 202205 branch
