Repository sonic-net/sonic-linkmgrd, pull requests merged in 2024-06, with the labels that each got.

#252 [action] [PR:250] [active-standby] add knob to enable/disable oscillation (#250)
  src/DbInterface.cpp
  src/MuxManager.h
  src/common/MuxConfig.h
  src/common/MuxPortConfig.h
  src/link_manager/LinkManagerStateMachineActiveStandby.cpp
  test/MuxManagerTest.cpp
  test/MuxManagerTest.h
Labels: automerge

#254 [active-standby] Fix default route handler race condition
  src/MuxPort.cpp
  test/FakeMuxPort.h
  test/LinkManagerStateMachineTest.cpp
  test/LinkManagerStateMachineTest.h
Labels: Request for 202305 Branch, Request for 202311 Branch, Request for 202405 Branch

#255 [action] [PR:254] [active-standby] Fix default route handler race condition (#254)
  src/MuxPort.cpp
  test/FakeMuxPort.h
  test/LinkManagerStateMachineTest.cpp
  test/LinkManagerStateMachineTest.h
Labels: automerge

#258 Fix default route race condition UT
  test/LinkManagerStateMachineTest.cpp
Labels: Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch, Cherry Pick Conflict_202405, Request for 202405 Branch

#259 [action] [PR:258] Fix default route race condition UT (#258)
  test/LinkManagerStateMachineTest.cpp
Labels: automerge
